### ISSUE TITLE
Get Diagnostic Line Number

### ISSUE THREAD

**Issue by XtremeDevX** [rslint/rslint#112]
So I was wondering if there way any way to get the line number of the error (which line the error occured in).

Nodejs shows you the error like so:
![image](https://user-images.githubusercontent.com/63039748/124384993-7ac6a580-dcf1-11eb-90c7-e06dbccbbb0d.png)

So i was wondering if there was any field in `Diagnostic` that gives you the line number.

**Comment by Stupremee** [comment]
The structure of a `Diagnostic` is really different. Not just a message, line combination. It consists of multiple `SubDiagnostic`s. The best way to get the line is using the `primary` field

**Comment by XtremeDevX** [comment]
@Stupremee so what field should I access? `primary.?`

**Comment by XtremeDevX** [comment]
Or do I have to manually calculate line number?

**Comment by Stupremee** [comment]
Yes most likely. Depending on the suggestion and what line number do you want.

**Comment by Stupremee** [comment]
If you see an error message with an error, and help / info stuff, then there are multiple child diagnostics

**Comment by XtremeDevX** [comment]
@Stupremee isn't this an essential diagnostic field however? Wouldn't you think it's hard to manually calculate?

**Comment by XtremeDevX** [comment]
Also - not to forget, it's expensive to do this every time you need a line number - it's so much easier if we could get a `line_no` field so that it's less expensive

**Comment by Stupremee** [comment]
You don't need to calculate it manually. `diag.primary.unwrap().span`

**Comment by XtremeDevX** [comment]
Yes, that gives me character range, not line number though 😅

**Comment by XtremeDevX** [comment]
Also lol 1 more question - the primary error message i get for the first post here is correct (something along the lines of expected `)`), however it's not able to suggest fixes

**Comment by Stupremee** [comment]
You can take a look into `rslint_errors`. It's not that expensive.
First, you collect all line starts using `rslint_errors::line_starts` and then you can do a simple binary search on the returned list:
```rust
line_starts
  .binary_search(&byte_index)
  .unwrap_or_else(|next_line| next_line - 1),
```

**Comment by Stupremee** [comment]
> Also 1 more question - the primary error message i get for the first post here is correct (something along the lines of expected `)`), however it's not able to suggest fixes

IIRC we don't suggest fixes for any parsing errors. Might be a good addition, but is also very hard to do correctly

**Comment by XtremeDevX** [comment]
agreed

**Comment by Stupremee** [comment]
Do you have discord or something else? Using github issues for stuff like this is annoying :sweat_smile:

**Comment by XtremeDevX** [comment]
Yes - XtremeDevX#0007
