### ISSUE TITLE
RSLint-parser does not produce uniform SinglePattern child.

### ISSUE THREAD

**Issue by HerringtonDarkholme** [rslint/rslint#120]
**I tried this code**:

```js
(a = b) => {} // a is under Name
({a = b}) => {} // a is under SinglePattern
```

**I expected this to happen**: 

RSLint should produce the identifier `a` under a node of `Name`.

**Instead this happened:**: 
RSLint  produce the identifier `a` under a node of `SinglePattern` for object destructuring. 
But for normal default JS parameter is under `Name`. 

### Meta 
I am directly using rslint-parser 0.3.0, as a rust library.

**Additional context**

Thanks for the great tool! The architecture is so nice and clean!. 
I am building a template compiler for Vue.JS in Rust. https://github.com/HerringtonDarkholme/vue-template-compiler
So I opted this great library for parsing JS.

I guess the cause is around https://github.com/rslint/rslint/blob/e7c7c2b62d7038e33dc64ceac86847b5462ca7dc/crates/rslint_parser/src/syntax/pat.rs#L247-L248

**Comment by HerringtonDarkholme** [comment]
More information, I tested code like this
![image](https://user-images.githubusercontent.com/2883231/135438317-79fcd66b-87f5-4c0f-bd8a-369faad483d0.png)

For simple single assignment, the children tree is
![image](https://user-images.githubusercontent.com/2883231/135438400-68bcbbe4-ef7e-4dd7-91f4-4d54f7d9f51e.png)

For single assignment under the object.
![image](https://user-images.githubusercontent.com/2883231/135438366-90f52ec0-2813-40d7-94b7-64030b36dd5f.png)

Relevant test is here https://github.com/HerringtonDarkholme/vue-template-compiler/blob/main/crates/compiler/src/util/rslint.rs#L91-L101

**Comment by HerringtonDarkholme** [comment]
![image](https://user-images.githubusercontent.com/2883231/135441303-30dbc993-e621-4943-ac25-81106fe965ea.png)

Note the NAME node is changed to SINGLE_PATTERN, I guess the problem occurs here.

**Comment by Stupremee** [comment]
Thanks for the compliments, the bug report and the fix :smile: !
