### ISSUE TITLE
[parser] Incorret types inside the AST of `continue` statement

### ISSUE THREAD

**Issue by ematipico** [rslint/rslint#126]
Given the following snippet:

```js
tour: while (true) {
	continue tour;
}
```

The `continue tour;` statement returns the following green node structure:

```
syntax: CONTINUE_STMT@50..63
 CONTINUE_KW@50..58 "continue"
 WHITESPACE@58..59 " "
 NAME_REF@59..63
  IDENT@59..63 "tour"
```

Although, the generated AST is not consistent:

```rs
impl ContinueStmt {
	pub fn continue_token(&self) -> Option<SyntaxToken> {
		support::token(&self.syntax, T![continue])
	}
	pub fn ident_token(&self) -> Option<SyntaxToken> { support::token(&self.syntax, T![ident]) }
	pub fn semicolon_token(&self) -> Option<SyntaxToken> { support::token(&self.syntax, T ! [;]) }
}

```

The `ident_token` returns a `SyntaxToken`, although the green token yields a `NameRef`. The end result is that calling `.ident_token()` will *always* return `None`.

Where is the bug? The green tree structure of the AST?

I am willing to fix the bug, I just want to know where to fix the bug.

**Comment by Stupremee** [comment]
Have a look at these two lines. I don't know why we parse the label as a expression, you can try to replace it with just parsing an ident and check if it breaks some existing tests.

https://github.com/rslint/rslint/blob/d8757de873c97244b6a82607c2227aed35922260/crates/rslint_parser/src/syntax/stmt.rs#L372

https://github.com/rslint/rslint/blob/d8757de873c97244b6a82607c2227aed35922260/crates/rslint_parser/src/syntax/stmt.rs#L335

**Comment by Stupremee** [comment]
```diff
diff --git a/crates/rslint_parser/src/syntax/stmt.rs b/crates/rslint_parser/src/syntax/stmt.rs
index 24868f5..89a5b24 100644
--- a/crates/rslint_parser/src/syntax/stmt.rs
+++ b/crates/rslint_parser/src/syntax/stmt.rs
@@ -333,6 +333,7 @@ pub fn break_stmt(p: &mut Parser) -> CompletedMarker {
         let end = p.cur_tok().range.end;
         let label = primary_expr(p).unwrap();
         check_label_use(p, &label);
+        label.undo_completion(p).abandon(p);
         end
     } else {
         start.end
@@ -372,6 +373,7 @@ pub fn continue_stmt(p: &mut Parser) -> CompletedMarker {
         let label = primary_expr(&mut *guard).unwrap();
         drop(guard);
         check_label_use(p, &label);
+        label.undo_completion(p).abandon(p);
         end
     } else {
         start.end

```

So that's basically the fix. Then just update the tests and should be ready
