### ISSUE TITLE
`ForOfStmt` missing from `ast::Stmt` enum

### ISSUE THREAD

**Issue by rickbutton** [rslint/rslint#130]
It looks like the `ForOfStmt` is missing from the `ast::Stmt` enum: https://github.com/rslint/rslint/blob/master/crates/rslint_parser/src/ast/stmt_ext.rs#L156-L157 , and the variety of places that conversion is done. Would be happy to submit a PR if requested.

**Comment by Stupremee** [comment]
Oh, interesting. Thanks for the catch! Sure you can open a PR
