### ISSUE TITLE
How to debug in VSCode

### ISSUE THREAD

**Issue by await-ovo** [rslint/rslint#132]
This is my `.vscode/launch.json`:

```json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "lldb",
      "request": "launch",
      "name": "Debug executable 'rslint'",
      "cargo": {
        "args": [
          "build",
          "--bin=rslint",
          "--package=rslint_cli"
        ],
        "filter": {
          "name": "rslint",
          "kind": "bin"
        }
      },
      "args": ["-f", "./tests/main.ts"],
      "cwd": "${workspaceFolder}",
    }
  ]
}
```

Should hit breakpoint in debugging, but it seems like not stopping on breakpoints:

https://user-images.githubusercontent.com/41503212/143224625-bd826fed-e464-4c02-ac12-07bcb9c929c6.mov
### Meta 
`rslint -V`:  0.3.1

If building from source:
`rustc --version --verbose`:
```
rustc 1.56.0 (09c42c458 2021-10-18)
binary: rustc
commit-hash: 09c42c45858d5f3aedfa670698275303a3d19afa
commit-date: 2021-10-18
host: x86_64-apple-darwin
release: 1.56.0
LLVM version: 13.0.0
```
I'm not sure if it's a problem with my vscode configuration.

I think it's possible to provide  `.vscode/launch.json` in the repository like [boa](https://github.com/boa-dev/boa/blob/main/.vscode/launch.json),[rust-analyzer](https://github.com/rust-analyzer/rust-analyzer/blob/master/.vscode/launch.json).

Also, it would be nice to have `CONTRIBUTING.md`. Thanks for your help.

**Comment by Stupremee** [comment]
Aren't you missing the `"sourceLanguages": ["rust"]` part? I guess it might be important

**Comment by await-ovo** [comment]
> Aren't you missing the `"sourceLanguages": ["rust"]` part? I guess it might be important

I've tried this,but it does't work.
I'd love to send a pr but I'm not familiar with toolchains when I'm just starting to learn rust.

**Comment by Stupremee** [comment]
Mhh okay. I might have to test myself, but that could take a few days because I need to set up VSCode first.

**Comment by await-ovo** [comment]
> Mhh okay. I might have to test myself, but that could take a few days because I need to set up VSCode first.


Hi @Stupremee, After reading [this documentation,](https://github.com/vadimcn/vscode-lldb/wiki/Breakpoints-are-not-getting-hit) I found that our repository turned off the generation of debug info, and [after change debug value  to 2](https://github.com/rslint/rslint/blob/master/Cargo.toml#L15), I was able to debug under VSCode normally.

![image](https://user-images.githubusercontent.com/41503212/143671678-81413112-553d-42f2-8e8b-75eaa8048408.png)

 I'm not sure if this configuration will affect the final released package, please check it for me~

**Comment by Stupremee** [comment]
That shouldn't affect the final release so I think it's finde
