### ISSUE TITLE
How can I adjust an AST node?

### ISSUE THREAD

**Issue by Vannevelj** [rslint/rslint#137]
I looked around for documentation on this but couldn't find any. For context, I'm trying to read a Javascript file and add TS types to it (essentially turning it into Typescript). I can read the file into an AST and find the variable declarations. I see that the type is contained at `declarator.pattern.ty()` but I wasn't able to figure out how to actually make changes to this.

Is there an example that demonstrates how we can make changes to the AST?

**Comment by Stupremee** [comment]
You can use the [`replace_with`](https://docs.rs/rowan/latest/rowan/api/struct.SyntaxNode.html#method.replace_with) method on `SyntaxNode`, which will clone the whole CST and replace the specified node with another one.

It's not possible to modify the CST without cloning it because one of it's core concepts is immutability

**Comment by Vannevelj** [comment]
@Stupremee thanks for pointing me in that direction! I see that function takes in a `GreenNode` which I can get from `ast::Pattern::SinglePattern.syntax().green()` but I'm struggling to see how I make changes to it. Looking through the code base I saw `GreenNode::new`, `GreenNodeBuilder` and `SyntaxTreeBuilder` as well but no examples of how I can change the data in these nodes.

For a concrete example, this is one approach I have so far:

```rs
fn replace_ast() {
    let parse = parse_text("const foo: number = 5;", 0);
    let ast = parse.syntax();

    for descendant in ast.descendants() {
        match descendant.kind() {
            rslint_parser::SyntaxKind::VAR_DECL => {
                let declaration = descendant.to::<rslint_parser::ast::VarDecl>();
                for declarator in declaration.declared() {
                    match declarator.pattern().unwrap() {
                        rslint_parser::ast::Pattern::SinglePattern(single) => {
                            let original_type = single.syntax();
                            let new_green = original_type.green().clone();
                            
                            original_type.replace_with(new_green)
                        },
                        _ => continue
                    };
                }
            },
            _ => continue
        }
    }
}
```

How do I go about changing `new_green`?

**Comment by Stupremee** [comment]
Now that I think about your use case, it's probably easier to use the approach we use for autofix in RSLint. 

If you have a look at [this](https://github.com/rslint/rslint/blob/master/crates/rslint_core/src/autofix/mod.rs), you can see how we change the source code. [Here](https://github.com/rslint/rslint/blob/master/crates/rslint_core/src/autofix/apply.rs#L33) is the logic for then applying the `Indel`s. 

However, if you really want to modify the CST, which has advantages too, you need to build a `GreenNode` using the [`GreenNodeBuilder`](https://docs.rs/rowan/latest/rowan/struct.GreenNodeBuilder.html). There are also examples in the [rowan](https://github.com/rust-analyzer/rowan/tree/master/examples) repository where they build `GreenNode`s using the builder.

**Comment by Vannevelj** [comment]
Thanks for these options! Ordinarily my preference would be to create new nodes and render the new AST but the `GreenNodeBuilder` API doesn't seem all that friendly (at least, I'm having a hard time figuring out how it's supposed to be used).

The `Indel` approach seems promising! I managed to get it working relatively painlessly once I figured out the imports:

```rs
fn replace_ast() {
    let source = "const foo = 5; // test";
    let parse = parse_text(source, 0);
    let ast = parse.syntax();
    let arc = Arc::from(source);
    let mut fixer = Fixer::new(arc);

    for descendant in ast.descendants() {
        match descendant.kind() {
            rslint_parser::SyntaxKind::VAR_DECL => {
                let declaration = descendant.to::<rslint_parser::ast::VarDecl>();
                for declarator in declaration.declared() {
                    match declarator.pattern().unwrap(){
                        rslint_parser::ast::Pattern::SinglePattern(single) => {
                            let span = single.name().unwrap().syntax().as_range();
                            fixer.insert_after(span, ": any");
                        },
                        _ => continue
                    };
                }
            },
            _ => continue
        }
    }

    let result = fixer.apply();
    println!("{result}");
}
```

Which prints

```
const foo: any = 5; // test
```

I'll incorporate this approach in my actual app instead of the playground and see where I get with this, thanks for all the help!
