### ISSUE TITLE
docs: http://rslint.org/ is down

### ISSUE THREAD

**Issue by gabrielcsapo** [rslint/rslint#154]
# Summary

Navigating to http://rslint.org/ is hard down 

<img width="1840" alt="Screen Shot 2022-11-28 at 3 35 48 PM" src="https://user-images.githubusercontent.com/1854811/204403020-5932debf-ad02-4313-834b-ea38ca9eed70.png">

**Comment by cwkang1998** [comment]
Its up now so let's close this?

**Comment by gabrielcsapo** [comment]
sounds good! @cwkang1998
