### ISSUE TITLE
Feature: add `rslint-ignore <rules> until <line>`

### ISSUE THREAD

**Issue by RDambrosio016** [rslint/rslint#23]
Currently rslint's ignore command is either scoped to the entire file or its scoped to the statement or declaration its on top of. This does not seem to be the norm apparently, i would like to keep scoping as it is and instead add a more explicit modifier to the ignore command as such:

ignoring an entire statement:

```js
// rslint-ignore no-empty
if (foo) {}
else {} // no error
```

ignoring a block of code until another line:

```js
// rslint-ignore no-empty until 5
{}
{}
{}
{}
{} // error
```

Perhaps we could also add `rslint-ignore <rules> until eof`? i really prefer an explicit command such as this over weird scoping you cannot make sense of, which is the case with eslint (in my opinion)

# Mentoring instructions 
To add this you will need to modify the directive parser which is found [here](https://github.com/RDambrosio016/RSLint/blob/master/rslint_core/src/directives/parser.rs), ignore commands are parsed [here](https://github.com/RDambrosio016/RSLint/blob/master/rslint_core/src/directives/parser.rs#L275). What i would personally do is add two more variants to the commands enum called `IgnoreRulesUntil(Vec<Box<dyn CstRule>>, Range<usize>)` and `IgnoreUntil(Range<usize>)` where the ranges are start and end byte indices. You will need to cache the byte indices of line starts in the directive parser which is very easy, you can simply do it once when the directive parser is created, you can get the source code text through `root_node.text().to_string()`. To parse the actual directive you can simply peek the lexer to see if the next token's text is `until` and then further peek to see if its a number or `eof`. Then to enforce the directives you can simply add something to [the place where rules are run](https://github.com/RDambrosio016/RSLint/blob/master/rslint_core/src/lib.rs#L96), run through all of the directives, if any directive applies to the rule (ignoreUntil applies to all rules, IgnoreRulesUntil only applies if the rule is contained) then go through all of the diagnostics returned, if the first primary label of the diagnostic's range start is included in the directive's range then simply remove the diagnostic (`Vec::retain` can do this easily).

You will also need to update the docs [here](https://github.com/RDambrosio016/RSLint/blob/master/docs/directives.md) to document this.

**Comment by cristianossd** [comment]
It seems interesting, @RDambrosio016! I want to work on it

**Comment by RDambrosio016** [comment]
Go ahead! i heard from somebody that the directive parser's lexer is giving incorrect ranges sometimes, you may have to fix that too 👀

**Comment by cristianossd** [comment]
@RDambrosio016, I think some references on your mentoring instructions should be updated. Nowadays, the parser path is [this one](https://github.com/RDambrosio016/RSLint/blob/master/crates/rslint_core/src/directives/parser.rs) and where rules are run is [that](https://github.com/RDambrosio016/RSLint/blob/master/crates/rslint_core/src/lib.rs). Is this right?

**Comment by RDambrosio016** [comment]
yeah sorry, we moved everything to `/crates` and i forgot to update everything 😄

**Comment by Stupremee** [comment]
Yea the directive parser is broken somewhere. You will have to fix it to use it. With some debugging it *should* be easy to find

**Comment by cristianossd** [comment]
Is it not better to create another issue to fix the parser or the broken part is strictly related to ignore rule feature?

**Comment by Stupremee** [comment]
The current code for ignore and stuff *works fine*, so you can fix everything that you need in your PR

**Comment by RDambrosio016** [comment]
closing as we have decided this is not currently worth it over a disable then enable directive as line number can change
