### ISSUE TITLE
Getter and Setter 'key' returns the wrong node

### ISSUE THREAD

**Issue by alidn** [rslint/rslint#83]
https://github.com/rslint/rslint/blob/5d30f0e40a9651aece28d79be9954511d9005211/xtask/src/ast.rs#L1179-L1185

Looks like the name of a Getter or Setter is not defined in the AST, so the `key` method returns the node corresponding to the `get` or `set` keywords.  Wouldn't it be better if it referred to the value name of the getter or setter?

I came across this issue in PR #82 

https://github.com/rslint/rslint/blob/5d30f0e40a9651aece28d79be9954511d9005211/crates/rslint_parser/src/ast/generated/nodes.rs#L1232

**Comment by RDambrosio016** [comment]
Looks like i missed this when i was making contextual keyword their own thing in the ts branch, this can be easily fixed by making get and set contextual keywords 👍

**Comment by RDambrosio016** [comment]
Fixed in https://github.com/rslint/rslint/commit/a215a0fc305e15592f04d65f5d95c39d0ef29258

**Comment by alidn** [comment]
Thank you!
