### ISSUE TITLE
Is there a way to configure 'ignored' directories list?

### ISSUE THREAD

**Issue by zero734kr** [rslint/rslint#88]
Hi, me again here.

I was experimenting with rslint, but after compiling TypeScript for js, rslint is trying to lint the ``dist`` directory too.

In the documentation, I was unable to find information on how to set the ignored directory list as ``.eslintignore`` in ESLint.

I would love it if I could open pull request, but I am still too new to rust (I practically only know how to print "hello world" out) and I will wait for a new version if there is no option to ignore it

Thanks for all

**Comment by RDambrosio016** [comment]
Currently there isn't but i am planning to add either `.rslintignore`, an ignored key in the config, or an ignore flag, or all of those.

**Comment by Stupremee** [comment]
That's definitely a good option. Does eslint also ignore files/folders that are inside the `.gitignore`? That sounds like a good idea

**Comment by zero734kr** [comment]
> That's definitely a good option. Does eslint also ignore files/folders that are inside the `.gitignore`? That sounds like a good idea

According to what I know, instead of using `.gitignore` itself they are using to config ``.eslintignore`` separately

**Comment by Stupremee** [comment]
@zero734kr Do you think it's a good idea to enable `.gitignore` support by default, and still have an extra `.rslintignore`?

**Comment by zero734kr** [comment]
I think support for ``.gitignore`` is better to be enabled when put ``.gitignore`` in the ``.rslintignore`` file (something like extending to other configurations. In this case, extending to other ignore config), because there are some js test files that are ignored and need to be linted too

**Comment by cwkang1998** [comment]
Right now is the feature for .rslintignore being worked on? If not can I help contribute?

**Comment by Stupremee** [comment]
I'm currently working on it, and I already have a working prototype that just needs some cleaning. However, I do not have much time right now so it might take a few days
